"""
Integration example demonstrating the full pipeline:
1. Generate editing plan from transcript using LLM
2. Extract stock footage decisions with search queries
3. Download stock footage from Pexels API

This example shows how the LLM generates appropriate search phrases
for stock footage based on the content being discussed.
"""

import json
import os
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from backend.features.editing_plan.generator import generate_editing_plan
from backend.features.pexels import download_stock_footage


def extract_stock_footage_decisions(editing_plan: list) -> list:
    """
    Extract all stock footage decisions from the editing plan.

    Args:
        editing_plan: The editing plan generated by the LLM.

    Returns:
        List of stock footage decisions with search queries.
    """
    stock_footage_decisions = []

    for decision in editing_plan:
        if decision.get("feature") == "insert_stock_footage":
            search_query = decision.get("parameters", {}).get("search_query")
            if search_query:
                stock_footage_decisions.append(
                    {
                        "start": decision["start"],
                        "end": decision["end"],
                        "search_query": search_query,
                        "reason": decision.get("reason", ""),
                    }
                )

    return stock_footage_decisions


def download_all_stock_footage(
    stock_footage_decisions: list, output_dir: str = "downloads/stock_footage"
) -> dict:
    """
    Download all stock footage based on the decisions.

    Args:
        stock_footage_decisions: List of stock footage decisions with search queries.
        output_dir: Directory to save downloaded videos.

    Returns:
        Dictionary mapping timestamps to downloaded file paths.
    """
    downloaded_footage = {}

    for i, decision in enumerate(stock_footage_decisions, 1):
        search_query = decision["search_query"]
        start = decision["start"]
        end = decision["end"]

        print(f"\n[{i}/{len(stock_footage_decisions)}] Downloading stock footage for:")
        print(f"  Time: {start:.2f}s - {end:.2f}s")
        print(f"  Search: '{search_query}'")
        if decision.get("reason"):
            print(f"  Reason: {decision['reason']}")

        try:
            # Download the stock footage
            video_path = download_stock_footage(
                search_query, output_dir=output_dir, quality="hd"
            )

            downloaded_footage[f"{start:.2f}-{end:.2f}"] = {
                "path": video_path,
                "search_query": search_query,
                "start": start,
                "end": end,
            }

            print(f"  ✓ Downloaded: {video_path}")

        except Exception as e:
            print(f"  ✗ Failed to download: {e}")

    return downloaded_footage


def main():
    """Run the integration demo."""
    # Sample podcast transcript about technology and nature
    sample_transcript = [
        {"start": 0.0, "end": 5.0, "text": "Welcome to Tech and Nature Podcast."},
        {
            "start": 5.0,
            "end": 12.0,
            "text": "Today we explore how technology is helping us understand ocean ecosystems.",
        },
        {
            "start": 12.0,
            "end": 18.0,
            "text": "Scientists are using AI to track marine life movements in real-time.",
        },
        {
            "start": 18.0,
            "end": 25.0,
            "text": "Drones equipped with cameras fly over coastal areas to monitor wildlife.",
        },
        {
            "start": 25.0,
            "end": 32.0,
            "text": "This technology helps us protect endangered species and preserve biodiversity.",
        },
        {
            "start": 32.0,
            "end": 38.0,
            "text": "In urban areas, smart sensors are monitoring air quality in real-time.",
        },
        {
            "start": 38.0,
            "end": 45.0,
            "text": "The data collected helps city planners create greener, healthier cities.",
        },
    ]

    print("=" * 80)
    print("STOCK FOOTAGE INTEGRATION DEMO")
    print("=" * 80)
    print("\nThis demo shows the complete pipeline:")
    print("1. LLM analyzes transcript and generates editing plan")
    print("2. Stock footage decisions include appropriate search queries")
    print("3. Stock footage is downloaded from Pexels API\n")

    # Check for Groq API key
    groq_key = os.getenv("API_KEY")
    if not groq_key:
        print("ERROR: API_KEY environment variable not set")
        print("\nTo run this demo:")
        print("  export API_KEY='your-groq-key-here'")
        print("  python examples/demo_stock_footage_integration.py")
        return 1

    # Check for Pexels API key
    pexels_key = os.getenv("PEXELS_API_KEY")
    if not pexels_key:
        print("ERROR: PEXELS_API_KEY environment variable not set")
        print("\nTo run this demo:")
        print("  export PEXELS_API_KEY='your-key-here'")
        print("  python examples/demo_stock_footage_integration.py")
        return 1

    print("Sample Transcript:")
    print("-" * 80)
    for segment in sample_transcript:
        print(f"[{segment['start']:.1f}s - {segment['end']:.1f}s] {segment['text']}")

    # Step 1: Generate editing plan
    print("\n" + "=" * 80)
    print("STEP 1: Generating Editing Plan with LLM")
    print("=" * 80)
    print("\nAsking the Groq LLM to analyze the content and suggest editing features...")
    print("(This may take 10-30 seconds)\n")

    try:
        editing_plan = generate_editing_plan(
            transcript=sample_transcript,
            api_key=groq_key,
            model="llama-3.3-70b-versatile",
            additional_context="This is a technology and nature podcast. Use stock footage to illustrate the concepts being discussed.",
        )

        print(f"✓ Generated {len(editing_plan)} editing decisions")

        # Save the full editing plan
        with open("editing_plan_with_stock_footage.json", "w") as f:
            json.dump(editing_plan, f, indent=2)
        print("✓ Full editing plan saved to: editing_plan_with_stock_footage.json")

    except Exception as e:
        print(f"✗ Error generating editing plan: {e}")
        return 1

    # Step 2: Extract stock footage decisions
    print("\n" + "=" * 80)
    print("STEP 2: Extracting Stock Footage Decisions")
    print("=" * 80 + "\n")

    stock_footage_decisions = extract_stock_footage_decisions(editing_plan)

    if not stock_footage_decisions:
        print("No stock footage decisions found in the editing plan.")
        return 0

    print(f"Found {len(stock_footage_decisions)} stock footage decisions:\n")
    for i, decision in enumerate(stock_footage_decisions, 1):
        print(f"{i}. [{decision['start']:.2f}s - {decision['end']:.2f}s]")
        print(f"   Search Query: '{decision['search_query']}'")
        if decision.get("reason"):
            print(f"   Reason: {decision['reason']}")
        print()

    # Step 3: Download stock footage
    print("=" * 80)
    print("STEP 3: Downloading Stock Footage from Pexels")
    print("=" * 80)

    downloaded_footage = download_all_stock_footage(stock_footage_decisions)

    # Summary
    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print(f"\nTotal editing decisions: {len(editing_plan)}")
    print(f"Stock footage decisions: {len(stock_footage_decisions)}")
    print(f"Successfully downloaded: {len(downloaded_footage)}")

    if downloaded_footage:
        print("\nDownloaded footage:")
        for timestamp, info in downloaded_footage.items():
            print(f"  • {timestamp}s: {info['search_query']} -> {info['path']}")

    # Save the mapping
    with open("stock_footage_mapping.json", "w") as f:
        json.dump(downloaded_footage, f, indent=2)
    print("\n✓ Stock footage mapping saved to: stock_footage_mapping.json")

    print("\n" + "=" * 80)
    print("Demo completed successfully!")
    print("=" * 80)

    return 0


if __name__ == "__main__":
    exit(main())
